In [2]:
1+1

2

In [4]:
# Numpy Library 
import numpy as np

In [5]:
list=[1,2,3,4]
arr=np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
## 2 dimension 
arr1.shape

(2, 3)

In [12]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr1.dtype

dtype('int32')

In [16]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [17]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [34]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [22]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [45]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.19223192, 0.26086103, 0.98871995],
       [0.93443267, 0.18275671, 0.678878  ]])

In [25]:
print("Random number following a Normal distribtuion with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribtuion with mean=0 and std=1
[[-0.84124838 -3.07067973  0.29068254]
 [ 0.52969806  0.74959971 -0.27915355]
 [ 1.61476261  1.22112966  2.34881709]
 [-0.62206239  1.05472119  0.39929115]
 [-0.23131235 -0.03280381 -2.07081289]]


In [26]:
np.random.randint(1,100,50)

array([78, 82, 68, 37, 37, 19, 67, 62, 76, 60, 39, 18, 27, 14, 46, 54, 46,
       17, 23, 67, 76, 24, 83, 24, 51,  9, 59, 76, 26, 75, 53, 75, 24, 26,
       54, 15, 97, 37, 63, 85, 63, 38, 54, 39, 56, 74, 81, 25, 16, 17])

In [27]:
np.random.randint(1,100,(4,4))

array([[37, 52, 49, 14],
       [40, 52, 12,  6],
       [24, 99, 51, 75],
       [ 8, 92, 45, 52]])

In [28]:
arr=np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
## Slicing

arr[2:7:3]

array([2, 5])

In [31]:
arr[-1:7:-1]

array([10,  9,  8])

In [32]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [33]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [34]:
arr1

array([[34, 73, 29, 71],
       [57, 77, 60, 91],
       [42, 12, 38, 98],
       [31, 17, 16, 42],
       [69, 14, 38, 26]])

In [35]:
arr1[3:,1:]

array([[17, 16, 42],
       [14, 38, 26]])

In [36]:
arr1[0:3,0:3]

array([[34, 73, 29],
       [57, 77, 60],
       [42, 12, 38]])

In [37]:
arr1[-3:-1,-3:-1]


array([[12, 38],
       [17, 16]])

In [38]:
## universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [39]:
arr1

array([[49, 86, 81],
       [44, 98, 93],
       [47, 94, 34]])

In [40]:
arr2

array([[60, 48, 99],
       [86, 94, 92],
       [83, 83, 48]])

In [41]:
arr1 + arr2

array([[109, 134, 180],
       [130, 192, 185],
       [130, 177,  82]])

In [42]:
arr1 * arr2

array([[2940, 4128, 8019],
       [3784, 9212, 8556],
       [3901, 7802, 1632]])

In [104]:
arr1 / arr2

array([[1.07894737, 3.69230769, 0.90909091],
       [1.52777778, 0.75555556, 0.65432099],
       [3.51851852, 0.97058824, 0.77319588]])

In [43]:
np.sqrt(arr1)

array([[7.        , 9.2736185 , 9.        ],
       [6.63324958, 9.89949494, 9.64365076],
       [6.8556546 , 9.69535971, 5.83095189]])

In [106]:
np.exp(arr2)

array([[1.01480039e+33, 1.95729609e+11, 4.60718663e+28],
       [4.31123155e+15, 3.49342711e+19, 1.50609731e+35],
       [5.32048241e+11, 5.83461743e+14, 1.33833472e+42]])

In [44]:
np.log10(arr1)

array([[1.69019608, 1.93449845, 1.90848502],
       [1.64345268, 1.99122608, 1.96848295],
       [1.67209786, 1.97312785, 1.53147892]])

In [45]:
arr1=np.arange(1,10)

In [46]:
arr1[2:]=1000

In [47]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [54]:
a1=[1,2,3,4,5]
a2=[6,7,8,9,10]

np.dot(a1, a2)

130

In [55]:
np.matmul(a1,a2)

130